"""Turn a graded lane into a running, named, registered Claude session.

The launch is built as data before anything runs: argv, the environment delta,
the working directory, and the PowerShell the terminal will execute. A test
reads that spec and never starts a process, which is the only way to prove what
a launcher does on a host where the thing it launches is interactive.

Two host facts this file is built on, both checked against the installed
binary rather than taken from documentation:

  `claude` takes `--name`, `--remote-control [name]`, `--model`, `--agent`,
  `--permission-mode` and a positional opening prompt.

  `CLAUDE_CODE_FORCE_SESSION_PERSISTENCE=1` is the supported way to keep a
  session that inherited a parent Claude's environment persistent and
  resumable. The launcher sets it and strips nothing: a lane that erased its
  parentage to look independent would be lying about where it came from.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable
import os
import shutil
import subprocess
import sys
import time

REGISTRATION_TIMEOUT = "SESSION_REGISTRATION_TIMEOUT"
REGISTERED_ELSEWHERE = "SESSION_REGISTERED_ELSEWHERE"
TERMINAL_MISSING = "TERMINAL_MISSING"
READY = "READY"

FORCED = {"CLAUDE_CODE_FORCE_SESSION_PERSISTENCE": "1"}
PRESERVED = ("CLAUDE_CODE_SESSION_ID", "CLAUDE_CODE_ENTRYPOINT", "CLAUDE_PID")

OPENING = ("Read {orders} and take ownership of the concern it describes. "
           "These are your standing orders for this session; do not wait for "
           "anyone to paste them again.")


def orders_text(lane: dict[str, Any]) -> str:
    """The prompt the session opens with.

    A file becomes a short instruction to read it rather than its contents.
    Orders long enough to be worth writing down are long enough to overrun the
    command line that would carry them, and a truncated order is worse than a
    missing one.
    """
    if lane.get("orders_file"):
        return OPENING.format(orders=lane["orders_file"])
    return str(lane.get("orders") or "")


def spec(lane: dict[str, Any], claude: str = "claude") -> dict[str, Any]:
    """The complete launch, as data. Nothing here starts a process."""
    argv = [claude, "--name", lane["name"]]
    if lane.get("remote_control", True):
        argv += ["--remote-control", lane["name"]]
    if lane.get("model"):
        argv += ["--model", lane["model"]]
    if lane.get("agent"):
        argv += ["--agent", lane["agent"]]
    if lane.get("mode") == "read-only":
        argv += ["--permission-mode", "plan"]
    argv.append(orders_text(lane))
    return {
        "lane": lane["name"],
        "argv": argv,
        "env": dict(FORCED, SOV_SESSION=lane["name"]),
        "cwd": lane["worktree"],
        "preserved": list(PRESERVED),
    }


def _ps_quote(value: str) -> str:
    """A PowerShell single-quoted literal; the only escape inside one is ''."""
    return "'" + str(value).replace("'", "''") + "'"


def script_text(launch: dict[str, Any]) -> str:
    """The PowerShell the lane's terminal runs.

    Written to a file rather than passed as `-Command`, because the orders
    travel through Windows Terminal into PowerShell into `claude`, and every
    layer of that has its own quoting. A file has none.
    """
    lines = ["# Generated by scripts/sov_hypervisor.py. Host plumbing; no standing.",
             "$ErrorActionPreference = 'Stop'"]
    for key, value in sorted(launch["env"].items()):
        lines.append(f"$env:{key} = {_ps_quote(value)}")
    lines.append("Set-Location -LiteralPath " + _ps_quote(launch["cwd"]))
    head, *rest = launch["argv"]
    args = ", ".join(_ps_quote(item) for item in rest)
    lines.append(f"& {_ps_quote(head)} @({args})")
    return "\n".join(lines) + "\n"


def write_script(launch: dict[str, Any], into: Path) -> Path:
    """Put the lane's script on disk where a human can read it afterwards."""
    into.mkdir(parents=True, exist_ok=True)
    path = into / f"{launch['lane']}.ps1"
    path.write_text(script_text(launch), encoding="utf-8", newline="\n")
    return path


class TerminalMissing(RuntimeError):
    """The host has no terminal to open the lane in.

    Declared as a refusal, so it is raised as one. Reaching `Popen` and letting
    `FileNotFoundError` escape would abandon lanes already started earlier in
    the same batch, unreported.
    """

    def __init__(self, terminal: str) -> None:
        super().__init__(f"{TERMINAL_MISSING}: {terminal} is not on PATH")
        self.refusal = TERMINAL_MISSING
        self.terminal = terminal


def terminal_available(terminal: str | None) -> bool:
    """Whether the host can open a window with this terminal, before any lane starts."""
    if not terminal:
        return True
    return shutil.which(terminal) is not None


def terminal_argv(launch: dict[str, Any], script: Path,
                  terminal: str | None = "wt.exe") -> list[str]:
    """How the host opens a window for this lane."""
    shell = ["powershell", "-NoProfile", "-NoExit", "-File", str(script)]
    if not terminal:
        return shell
    return [terminal, "new-tab", "--title", launch["lane"],
            "-d", launch["cwd"], *shell]


def environment(launch: dict[str, Any],
                base: dict[str, str] | None = None) -> dict[str, str]:
    """The child's environment: the parent's, plus what the lane needs.

    Nothing is removed. Whatever recorded that this process was started by
    another Claude session stays recorded; persistence is bought with the
    documented override, not by hiding the parent.
    """
    env = dict(os.environ if base is None else base)
    env.update(launch["env"])
    return env


def start(launch: dict[str, Any], script: Path, terminal: str | None = "wt.exe",
          base: dict[str, str] | None = None) -> subprocess.Popen[bytes]:
    """Open the lane's window. Returns the terminal process, not the session."""
    argv = terminal_argv(launch, script, terminal)
    flags = 0
    if sys.platform == "win32" and not terminal:
        flags = getattr(subprocess, "CREATE_NEW_CONSOLE", 0)
    try:
        return subprocess.Popen(argv, cwd=launch["cwd"],
                                env=environment(launch, base), creationflags=flags)
    except FileNotFoundError as error:
        raise TerminalMissing(argv[0]) from error


def await_registration(name: str, tree: str, read: Callable[[], dict[str, Any]],
                       timeout: float = 90.0, interval: float = 1.5,
                       clock: Callable[[], float] = time.monotonic,
                       sleep: Callable[[float], None] = time.sleep) -> dict[str, Any]:
    """Wait until the registry sees this lane, or say plainly that it did not.

    A launched process is not a lane. Reporting one as ready before its own
    SessionStart hook has registered it is the claim this refuses to make.
    """
    deadline = clock() + timeout
    while True:
        record = (read() or {}).get(name)
        if record and record.get("live"):
            seen = str(record.get("tree") or "").replace("\\", "/")
            want = str(tree).replace("\\", "/")
            if seen.rstrip("/").lower() != want.rstrip("/").lower():
                return {"lane": name, "verdict": REGISTERED_ELSEWHERE,
                        "refusal": REGISTERED_ELSEWHERE,
                        "because": f"{name} registered in {seen}, not {want}"}
            return {"lane": name, "verdict": READY, "pid": record.get("pid"),
                    "tree": seen, "branch": record.get("branch")}
        if clock() >= deadline:
            return {"lane": name, "verdict": REGISTRATION_TIMEOUT,
                    "refusal": REGISTRATION_TIMEOUT,
                    "because": f"{name} did not register within {timeout:.0f}s; "
                               "the window may be open and the session unstarted"}
        sleep(interval)
